// <auto-generated />
using System;
using BlazorApp4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp4.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20240611022406_QuanLyKho1")]
    partial class QuanLyKho1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp4.Models.DonViTinh", b =>
                {
                    b.Property<int>("donViTinh_Auto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("donViTinh_Auto_ID"));

                    b.Property<string>("ghiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("tenDonViTinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("donViTinh_Auto_ID");

                    b.HasIndex("tenDonViTinh")
                        .IsUnique();

                    b.ToTable("donViTinh");
                });

            modelBuilder.Entity("BlazorApp4.Models.Kho", b =>
                {
                    b.Property<int>("kho_Auto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("kho_Auto_ID"));

                    b.Property<string>("ghiChu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tenKho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("kho_Auto_ID");

                    b.HasIndex("tenKho")
                        .IsUnique();

                    b.ToTable("kho");
                });

            modelBuilder.Entity("BlazorApp4.Models.Kho_User", b =>
                {
                    b.Property<int>("khoUser_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("khoUser_ID"));

                    b.Property<int>("kho_Auto_ID")
                        .HasColumnType("int");

                    b.Property<string>("maDangNhap")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("khoUser_ID");

                    b.HasIndex("kho_Auto_ID");

                    b.HasIndex("maDangNhap");

                    b.ToTable("kho_user");
                });

            modelBuilder.Entity("BlazorApp4.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("loaiSanPham_Auto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("loaiSanPham_Auto_ID"));

                    b.Property<string>("ghiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("maLoaiSanPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tenLoaiSanPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("loaiSanPham_Auto_ID");

                    b.HasIndex("maLoaiSanPham")
                        .IsUnique();

                    b.HasIndex("tenLoaiSanPham")
                        .IsUnique();

                    b.ToTable("loaiSanPham");
                });

            modelBuilder.Entity("BlazorApp4.Models.NhaCungCap", b =>
                {
                    b.Property<int>("nhaCungCap_Auto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nhaCungCap_Auto_ID"));

                    b.Property<string>("ghiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("maNhaCungcap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tenNhaCungcap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("nhaCungCap_Auto_ID");

                    b.HasIndex("maNhaCungcap")
                        .IsUnique();

                    b.ToTable("nhaCungCap");
                });

            modelBuilder.Entity("BlazorApp4.Models.Nhap_Kho", b =>
                {
                    b.Property<int>("nhapkho_Auto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nhapkho_Auto_ID"));

                    b.Property<string>("ghiChu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("kho_Auto_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayNhapKho")
                        .HasColumnType("datetime2");

                    b.Property<int>("nhaCungCap_Auto_ID")
                        .HasColumnType("int");

                    b.Property<string>("soPhieuNhapKho")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("0");

                    b.HasKey("nhapkho_Auto_ID");

                    b.HasIndex("kho_Auto_ID");

                    b.HasIndex("nhaCungCap_Auto_ID");

                    b.HasIndex("soPhieuNhapKho")
                        .IsUnique();

                    b.ToTable("nhapKho");
                });

            modelBuilder.Entity("BlazorApp4.Models.Nhap_Kho_Raw_Data", b =>
                {
                    b.Property<int>("nhapKhoRawData_Auto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nhapKhoRawData_Auto_ID"));

                    b.Property<decimal>("donGiaNhap")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("nhapkho_Auto_ID")
                        .HasColumnType("int");

                    b.Property<int>("sanPham_Auto_ID")
                        .HasColumnType("int");

                    b.Property<int>("soLuongNhap")
                        .HasColumnType("int");

                    b.HasKey("nhapKhoRawData_Auto_ID");

                    b.HasIndex("nhapkho_Auto_ID");

                    b.HasIndex("sanPham_Auto_ID");

                    b.ToTable("nhap_Kho_Raw_Data");
                });

            modelBuilder.Entity("BlazorApp4.Models.SanPham", b =>
                {
                    b.Property<int>("sanPham_Auto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sanPham_Auto_ID"));

                    b.Property<int>("donViTinh_Auto_ID")
                        .HasColumnType("int");

                    b.Property<string>("ghiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("loaiSanPham_Auto_ID")
                        .HasColumnType("int");

                    b.Property<string>("maSanPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tenSanpham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("sanPham_Auto_ID");

                    b.HasIndex("donViTinh_Auto_ID");

                    b.HasIndex("loaiSanPham_Auto_ID");

                    b.HasIndex("maSanPham")
                        .IsUnique();

                    b.ToTable("sanPham");
                });

            modelBuilder.Entity("BlazorApp4.Models.User", b =>
                {
                    b.Property<int>("user_Auto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_Auto_ID"));

                    b.Property<string>("ghiChu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("maDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("matKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("user_Auto_ID");

                    b.HasIndex("maDangNhap")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("BlazorApp4.Models.XuatKho", b =>
                {
                    b.Property<int>("xuatKho_Auto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("xuatKho_Auto_ID"));

                    b.Property<int>("Kho_ID")
                        .HasColumnType("int");

                    b.Property<string>("ghiChu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ngayXuatKho")
                        .HasColumnType("datetime2");

                    b.Property<string>("soPhieuXuatKho")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("xuatKho_Auto_ID");

                    b.HasIndex("Kho_ID");

                    b.HasIndex("soPhieuXuatKho")
                        .IsUnique();

                    b.ToTable("xuatKho");
                });

            modelBuilder.Entity("BlazorApp4.Models.Xuat_Kho_Raw_Data", b =>
                {
                    b.Property<int>("xuatKhoRawData_Auto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("xuatKhoRawData_Auto_ID"));

                    b.Property<decimal>("donGiaXuat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("sanPham_ID")
                        .HasColumnType("int");

                    b.Property<int>("soLuongXuat")
                        .HasColumnType("int");

                    b.Property<int>("xuatKho_ID")
                        .HasColumnType("int");

                    b.HasKey("xuatKhoRawData_Auto_ID");

                    b.HasIndex("sanPham_ID");

                    b.HasIndex("xuatKho_ID");

                    b.ToTable("xuat_Kho_Raw_Data");
                });

            modelBuilder.Entity("BlazorApp4.Models.Kho_User", b =>
                {
                    b.HasOne("BlazorApp4.Models.Kho", "kho")
                        .WithMany("kho_user")
                        .HasForeignKey("kho_Auto_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Kho_User_Kho");

                    b.HasOne("BlazorApp4.Models.User", "user")
                        .WithMany("kho_user")
                        .HasForeignKey("maDangNhap")
                        .HasPrincipalKey("maDangNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Kho_User_User");

                    b.Navigation("kho");

                    b.Navigation("user");
                });

            modelBuilder.Entity("BlazorApp4.Models.Nhap_Kho", b =>
                {
                    b.HasOne("BlazorApp4.Models.Kho", "kho")
                        .WithMany("nhapKho")
                        .HasForeignKey("kho_Auto_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Nhap_Kho_Kho");

                    b.HasOne("BlazorApp4.Models.NhaCungCap", "nhaCungCap")
                        .WithMany("nhap_Kho")
                        .HasForeignKey("nhaCungCap_Auto_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Nhap_Kho_NhaCungCap");

                    b.Navigation("kho");

                    b.Navigation("nhaCungCap");
                });

            modelBuilder.Entity("BlazorApp4.Models.Nhap_Kho_Raw_Data", b =>
                {
                    b.HasOne("BlazorApp4.Models.Nhap_Kho", "nhapKho")
                        .WithMany("nhap_Kho_Raw_Data")
                        .HasForeignKey("nhapkho_Auto_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Nhap_Kho_Raw_Data_Nhap_Kho");

                    b.HasOne("BlazorApp4.Models.SanPham", "sanPham")
                        .WithMany("nha_kho_raw_data")
                        .HasForeignKey("sanPham_Auto_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Nhap_Kho_Raw_Data_SanPham");

                    b.Navigation("nhapKho");

                    b.Navigation("sanPham");
                });

            modelBuilder.Entity("BlazorApp4.Models.SanPham", b =>
                {
                    b.HasOne("BlazorApp4.Models.DonViTinh", "donViTinh")
                        .WithMany("sanPham")
                        .HasForeignKey("donViTinh_Auto_ID")
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_DonViTinh");

                    b.HasOne("BlazorApp4.Models.LoaiSanPham", "loaiSanPham")
                        .WithMany("sanPham")
                        .HasForeignKey("loaiSanPham_Auto_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_LoaiSanPham");

                    b.Navigation("donViTinh");

                    b.Navigation("loaiSanPham");
                });

            modelBuilder.Entity("BlazorApp4.Models.XuatKho", b =>
                {
                    b.HasOne("BlazorApp4.Models.Kho", "kho")
                        .WithMany("xuatKho")
                        .HasForeignKey("Kho_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_XuatKho_Kho");

                    b.Navigation("kho");
                });

            modelBuilder.Entity("BlazorApp4.Models.Xuat_Kho_Raw_Data", b =>
                {
                    b.HasOne("BlazorApp4.Models.SanPham", "sanPham")
                        .WithMany("xuat_Kho_Raw_Data")
                        .HasForeignKey("sanPham_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Xuat_Kho_Raw_Data_SanPham");

                    b.HasOne("BlazorApp4.Models.XuatKho", "xuatKho")
                        .WithMany("xuat_Kho_Raw_Data")
                        .HasForeignKey("xuatKho_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Xuat_Kho_Raw_Data_XuatKho");

                    b.Navigation("sanPham");

                    b.Navigation("xuatKho");
                });

            modelBuilder.Entity("BlazorApp4.Models.DonViTinh", b =>
                {
                    b.Navigation("sanPham");
                });

            modelBuilder.Entity("BlazorApp4.Models.Kho", b =>
                {
                    b.Navigation("kho_user");

                    b.Navigation("nhapKho");

                    b.Navigation("xuatKho");
                });

            modelBuilder.Entity("BlazorApp4.Models.LoaiSanPham", b =>
                {
                    b.Navigation("sanPham");
                });

            modelBuilder.Entity("BlazorApp4.Models.NhaCungCap", b =>
                {
                    b.Navigation("nhap_Kho");
                });

            modelBuilder.Entity("BlazorApp4.Models.Nhap_Kho", b =>
                {
                    b.Navigation("nhap_Kho_Raw_Data");
                });

            modelBuilder.Entity("BlazorApp4.Models.SanPham", b =>
                {
                    b.Navigation("nha_kho_raw_data");

                    b.Navigation("xuat_Kho_Raw_Data");
                });

            modelBuilder.Entity("BlazorApp4.Models.User", b =>
                {
                    b.Navigation("kho_user");
                });

            modelBuilder.Entity("BlazorApp4.Models.XuatKho", b =>
                {
                    b.Navigation("xuat_Kho_Raw_Data");
                });
#pragma warning restore 612, 618
        }
    }
}
